[theme]
primaryColor = "#1B7FA5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F4F2"
textColor = "#3B3B3B"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
